version: 2
updates:
  - package-ecosystem: "github-actions" # Specify GitHub Actions dependencies
    directory: "/" # Root directory of the repository
    schedule:
      interval: "daily" # Check for updates daily
  - package-ecosystem: "pip" # Specify Python dependencies
    directory: "/" # Location of the requirements.txt file
    schedule:
      interval: "daily" # Check for updates daily
